# Generated by Django 2.0.5 on 2018-05-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='qid',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='action',
            name='user',
            field=models.IntegerField(),
        ),
    ]
