# Generated by Django 2.0.5 on 2018-08-31 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180831_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='correct',
            field=models.IntegerField(choices=[(True, 1), (False, 0)], default=0),
        ),
    ]
