# Generated by Django 2.0.5 on 2018-05-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='unique_id',
            field=models.CharField(default='43f37224e8e34ced8587', max_length=20, unique=True),
        ),
    ]
