# Generated by Django 2.0.5 on 2018-06-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20180602_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qid',
            field=models.CharField(editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
