# Generated by Django 2.0.5 on 2018-05-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20180521_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='unique_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
