# Generated by Django 2.0.5 on 2018-05-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_auto_20180521_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qid',
            field=models.CharField(default='66553741275041ecb7d82299684b8226', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
