# Generated by Django 2.0.5 on 2018-05-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_auto_20180521_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qid',
            field=models.CharField(default='3b8f17472c364a77b9632a0bcbc3b25c', editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
