# Generated by Django 2.0.5 on 2018-05-21 19:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_auto_20180521_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
