# Generated by Django 2.0.5 on 2018-05-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(choices=[(True, 'Correct'), (False, 'Incorrect')], default=False),
        ),
    ]
